Introduce TLdapClient NETBIOSDomainName property
synopse/mORMot2 pull request #150
Opened 2023-03-01 11:09 UTC by AndreasLrx

- Also change TLdapResult CopyObjectSid method

2023-03-01 14:34 UTC, synopse requested changes

2023-03-01 14:34 UTC, synopse commented on src/net/mormot.net.ldap.pas
> +  NetbiosObject := SearchFirst('CN=Partitions,CN=Configuration,' + RootDN, '(nETBIOSName=*)', ['nETBIOSName']);
memory leak?

2023-03-02 08:03 UTC, AndreasLrx commented on src/net/mormot.net.ldap.pas
> +  NetbiosObject := SearchFirst('CN=Partitions,CN=Configuration,' + RootDN, '(nETBIOSName=*)', ['nETBIOSName']);
The NetbiosObject has the same lifetime as the TLdapClient.SearchResult and doesn't have to be free here

2023-03-02 09:59 UTC, synopse approved these changes

2023-03-02 09:59 UTC, synopse commented on src/net/mormot.net.ldap.pas
> +  NetbiosObject := SearchFirst('CN=Partitions,CN=Configuration,' + RootDN, '(nETBIOSName=*)', ['nETBIOSName']);
you are right of course

2023-03-02 09:59 UTC, merged

2023-03-02 10:10 UTC, synopse commented
https://github.com/synopse/mORMot2/commit/8a2f92ea
would fix a potential buffer overflow reading - we need to use RawSid and not a pointer to validate the length of the binary input.