TOrmPropInfoRttiDynArray.SetValue: Try to base64magic decode T*ObjArrays as well.
synopse/mORMot2 pull request #56
Opened 2021-09-24 15:52 UTC by transmogrifix

The ORM saves my T*ObjArray property as a base64magic encoded blob. I noticed that the property was empty when loaded from the DB.

2021-09-24 19:25 UTC, synopse requested changes
The ORM should not save the T*ObjArray as Base64 but as JSON.
So the fix is to be done at saving, not at loading.

2021-09-24 19:27 UTC, transmogrifix commented
I wasn't sure, thanks! I'll look into it.

2021-09-24 20:24 UTC, transmogrifix commented
Actually, the data in the DB is not Base64, it is JSON. I missed it because it is in a `bytea` column (PostgreSQL) and pgAdmin4 does not show content, just displays `[binary data]`. 
So it is being base64 encoded somewhere after it is fetched from the DB.

2021-09-24 21:02 UTC, transmogrifix commented
It is being Base64 encoded in `TSqlDBPostgresStatement.ColumnsToJson(WR: TJsonWriter)` because column type is ftBlob.
I am unsure how to proceed. OrmFieldType for this property is oftBlobDynArray which maps to ftBlob.

2021-09-25 09:45 UTC, synopse commented
It should be ftUtf8 for T*ObjArray.
Please try with my latest commit above.

2021-09-27 07:59 UTC, transmogrifix commented
That fixed it. The column is now text, not bytea so the issue no longer exists.
The refactored code looks much better. 
Thank you!

2021-09-27 07:59 UTC, closed without merging